### ISSUE TITLE
 Wierd characters

### ISSUE THREAD

**Issue by thehilde** [bundesAPI/strukturen-ml#3]
Found some extra wierd characters, i think it's a LaTeX property .....
def replace_weird_characters(text):
    """sometimes some wierd unicode characters appear - lets just replace them for now and care about it later™"""
    replacementDict = {"�":"ti", "ﬀ":"ff", "ﬁ": "fi", "ﬂ": "fl", "ﬃ": "ffi", "ﬄ": "ffl"}
    for key in replacementDict.keys():
        if key in text:
            text = text.replace(key, replacementDict[key])
    return text

**Comment by LilithWittmann** [comment]
oh nice, do you want to open a pr?

**Comment by thehilde** [comment]
Yes.
